services:
  - type: web
    name: srms-python
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
